version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:latest
    container_name: db-pg
    restart: unless-stopped
    hostname: "127.0.0.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DATABASE: postgres
  mongodb:
    image: mongo:latest
    container_name: db-mg
    restart: unless-stopped
    hostname: "127.0.0.1"
    ports:
      - "27017:27017"
