"""Init

Revision ID: 308012c713b9
Revises: e176e62958c9
Create Date: 2022-12-23 01:01:41.948637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308012c713b9'
down_revision = 'e176e62958c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
